{"name": "test_create_same_user", "status": "passed", "description": "Получение статус-кода и сообщения об ошибке при попытке создать уже существующего пользователя", "start": 1726249409954, "stop": 1726249410282, "uuid": "a137210f-71e5-4077-b16a-da96ac34467a", "historyId": "ae81addda8cc645fffa2281f2abe0c06", "testCaseId": "ae81addda8cc645fffa2281f2abe0c06", "fullName": "tests.test_create_user.TestCreateUser#test_create_same_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "DESKTOP-ODIODOM"}, {"name": "thread", "value": "6972-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}